name: DevOps Lab - CI

on:
  pull_request:
    types:
      - opened
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23

      - name: Install golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.62

      - name: Build
        run: make build

      - name: Run Tests
        run: go test -v ./... -coverprofile=coverage.txt

      - name: Upload Coverage result to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.txt
          verbose: true
